### PR TITLE
Fixes a couple of minor bugs.

### PR DESCRIPTION
**Pull request by pocketarc**
Hi, thanks for your work on this library for Omnipay! I've just recently had to integrate it into a client's project, and came across a few minor issues, that I've since resolved (and I figured you might want them for your own repository).

There were three issues:

* `encrypt()`/`decrypt()` might collide with other projects quite easily. They've been renamed (ideally they should be namespaced, but that's not my call).
* The `delivery_name` option was using the valued passed to `billing_name`, and not the right value.
* The `tid` and `order_id` fields are different in CCAvenue, and have different validation rules. I don't know the `tid` field; I haven't seen it in any documentation for CCAvenue. Either way, I needed to specify a separate `order_id` and wasn't able to. This PR resolves that.

### CODE REVIEW

**Comment by gowrav-vishwakarma** [comment]
Hi,
Thank you for your pull requests, We are evaluating changes effected due to this. Since this code is part of much bigger product http://epan.in ...
Once checked on existing installations we will merge the code.

**Comment by pocketarc** [comment]
No problem, I completely understand. I've just had a need for this package and needed to set the order ID, and wasn't able to (and the encrypt/decrypt functions were colliding with the ones in my project).

Also, it'd be good if the license could be clarified. Is this an MIT-licensed bit of code? Am I allowed to use it?

**Comment by gowrav-vishwakarma** [comment]
Yes, sure, you are welcome to use this code 👍

**Comment by gowrav-vishwakarma** [comment]
Hey Bruno,

Are these the only changes you found required, or is there anything else ?

**Pull request merged**
